[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

# Redirects for SPA (Single Page Application) with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200